##:Simple-Language; :##
##:Engine: Pattern;
##:Parser: PatternCompiler;

##:SubLang {
	net.nawaman.curry.compiler.ExecutableCreator_Java;
}

##:TextProcessor {
	f     : net.nawaman.curry.compiler.TextProcessor_StringFormat;
	format: net.nawaman.curry.compiler.TextProcessor_StringFormat;
	c     : net.nawaman.curry.compiler.TextProcessor_Curry;
	curry : net.nawaman.curry.compiler.TextProcessor_Curry;
}
